In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3'],
                    'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']}, 
                   index = [0, 1, 2, 3])

df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                    'B' : ['B4', 'B5', 'B6', 'B7'],
                    'C' : ['C4', 'C5', 'C6', 'C7'],
                    'D' : ['D4', 'D5', 'D6', 'D7']}, 
                   index = [4, 5, 6, 7])

df3 = pd.DataFrame({'A' : ['A8', 'A9', 'A10', 'A11'],
                    'B' : ['B8', 'B9', 'B10', 'B11'],
                    'C' : ['C8', 'C9', 'C10', 'C11'],
                    'D' : ['D8', 'D9', 'D10', 'D11']}, 
                   index = [8, 9, 10, 11])

# concat

In [5]:
# concat : 데이터 병합
pd.concat([df1, df2, df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [6]:
pd.concat([df1, df2, df3], axis = 1)
#인덱스 번호가 다르면 제대로 병합되지 않는다.

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [7]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3'],
                    'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']}, 
                   index = [0, 1, 2, 3])

df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                    'B' : ['B4', 'B5', 'B6', 'B7'],
                    'C' : ['C4', 'C5', 'C6', 'C7'],
                    'D' : ['D4', 'D5', 'D6', 'D7']}, 
                   index = [0, 1, 2, 3])

df3 = pd.DataFrame({'A' : ['A8', 'A9', 'A10', 'A11'],
                    'B' : ['B8', 'B9', 'B10', 'B11'],
                    'C' : ['C8', 'C9', 'C10', 'C11'],
                    'D' : ['D8', 'D9', 'D10', 'D11']}, 
                   index = [0, 1, 2, 3])

In [8]:
# 인덱스 번호 같게 해주면 제대로 병합된다.
pd.concat([df1, df2, df3], axis = 1)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [15]:
# 다시 원래대로
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3'],
                    'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']}, 
                   index = [0, 1, 2, 3])

df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                    'B' : ['B4', 'B5', 'B6', 'B7'],
                    'C' : ['C4', 'C5', 'C6', 'C7'],
                    'D' : ['D4', 'D5', 'D6', 'D7']}, 
                   index = [4, 5, 6, 7])

df3 = pd.DataFrame({'A' : ['A8', 'A9', 'A10', 'A11'],
                    'B' : ['B8', 'B9', 'B10', 'B11'],
                    'C' : ['C8', 'C9', 'C10', 'C11'],
                    'D' : ['D8', 'D9', 'D10', 'D11']}, 
                   index = [8, 9, 10, 11])

In [16]:
df4 = pd.DataFrame({'B' : ['B2', 'B3', 'B6', 'B7'],
                    'D' : ['D2', 'D3', 'D6', 'D7'],
                    'F' : ['F2', 'F3', 'F6', 'F7']},
                    index = [2, 3, 6, 7])

In [17]:
# outer join
# 모든 것을 합치겠다.
result = pd.concat([df1, df4], axis = 1)
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [18]:
# inner join
# 병합할 데이터의 공통된 인덱스 값만 추출
result = pd.concat([df1, df4], axis = 1, join = 'inner')
result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [19]:
# 파이썬 버젼과 pandas 버젼이 다를때 오류 생기기도 한다. 이럴 땐 밑에 처럼 하기
result = pd.concat([df1, df4], axis = 1, join_axes = [df1.index])
result

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [25]:
# df1과 df4의 아웃터 조인한 값 중에서 df1에 해당하는 부분만 가져옴
result = pd.concat([df1, df4], axis = 1).reindex(df1.index)
result

    A   B   C   D    B    D    F
0  A0  B0  C0  D0  NaN  NaN  NaN
1  A1  B1  C1  D1  NaN  NaN  NaN
2  A2  B2  C2  D2   B2   D2   F2
3  A3  B3  C3  D3   B3   D3   F3

In [26]:
# df1과 df4의 아웃터 조인한 값 중에서 df4에 해당하는 부분만 가져옴
result = pd.concat([df1, df4], axis = 1).reindex(df4.index)
result

     A    B    C    D   B   D   F
2   A2   B2   C2   D2  B2  D2  F2
3   A3   B3   C3   D3  B3  D3  F3
6  NaN  NaN  NaN  NaN  B6  D6  F6
7  NaN  NaN  NaN  NaN  B7  D7  F7

In [28]:
# ignore_index
# index값들을 무시하고 데이터프레임을 병합
result = pd.concat([df1, df4], ignore_index = True)
result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [44]:
# merge 함수

df5 = pd.DataFrame({'key' : ['K0', 'K2', 'K3', 'K4'],
                    'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3']})

df6 = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                    'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']})

In [45]:
df5

  key   A   B
0  K0  A0  B0
1  K2  A1  B1
2  K3  A2  B2
3  K4  A3  B3

In [46]:
df6

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [49]:
pd.merge(df5, df6, on = "key")

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K2  A1  B1  C2  D2
2  K3  A2  B2  C3  D3

In [48]:
# how속성
# left, right, outer, inner
pd.merge(df5, df6, how = 'left', on = 'key')

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K2  A1  B1   C2   D2
2  K3  A2  B2   C3   D3
3  K4  A3  B3  NaN  NaN

In [50]:
pd.merge(df5, df6, how = 'right', on = 'key')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K2   A1   B1  C2  D2
2  K3   A2   B2  C3  D3
3  K1  NaN  NaN  C1  D1

In [51]:
# merge에서는 key값의 모든 것을 기준으로 나열한다.
pd.merge(df5, df6, how = 'outer', on = 'key')

  key    A    B    C    D
0  K0   A0   B0   C0   D0
1  K2   A1   B1   C2   D2
2  K3   A2   B2   C3   D3
3  K4   A3   B3  NaN  NaN
4  K1  NaN  NaN   C1   D1

In [76]:
pd.merge(df5, df6, how = 'inner', on = 'key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K2  A1  B1  C2  D2
2  K3  A2  B2  C3  D3

In [132]:
#df2015
#df2016
#df2017

df2015 = pd.read_csv("2015.csv", encoding = "euc_kr", index_col =  "관서명")
df2016 = pd.read_csv("2016.csv", encoding = "euc_kr", index_col = "관서명")
df2017 = pd.read_csv("2017.csv", encoding = "euc_kr", index_col = "관서명")
df2015

            구분  살인  강도  강간·강제추행    절도     폭력
관서명
광주지방경찰청계  발생건수  18  44      750  8425   9593
광주지방경찰청계  검거건수  18  47      758  5409   8301
광주지방경찰청계  검거인원  17  66      776  3433  11774
광주지방경찰청계    구속   9  33       42   104     58
광주지방경찰청계   불구속   1  26      511  2781   5618
광주지방경찰청계    기타   7   7      223   548   6098
광주동부경찰서   발생건수   3   5       92  1100   1155
광주동부경찰서   검거건수   4   6       86   583    970
광주동부경찰서   검거인원   4   7       98   447   1483
광주동부경찰서     구속   3   2        8    13     10
광주동부경찰서    불구속   0   4       63   379    703
광주동부경찰서     기타   1   1       27    55    770
광주서부경찰서   발생건수   5  10      172  2050   2483
광주서부경찰서   검거건수   4   8      153  1471   2124
광주서부경찰서   검거인원   4  15      167   876   3080
광주서부경찰서     구속   3  10        7    27     19
광주서부경찰서    불구속   0   5       91   665   1366
광주서부경찰서     기타   1   0       69   184   1695
광주남부경찰서   발생건수   1   3       70   962   1081
광주남부경찰서   검거건수   1   3       53   506    941
광주남부경찰서   검거인원   1   3       52   418   1260
광주남부경찰서     구속   0   3        3    19      3
광주남부경찰서    불구속   1   0       39   325    675
광주남부경찰서     기타   0   0       10    74    582
광주북부경찰서   발생건수   5  14      256  2570   2621
광주북부경찰서   검거건수   5  18      212  1852   2319
광주북부경찰서   검거인원   5  28      216   948   3168
광주북부경찰서     구속   3  11       11    30     10
광주북부경찰서    불구속   0  12      153   770   1544
광주북부경찰서     기타   2   5       52   148   1614
광주광산경찰서   발생건수   4  12      160  1743   2253
광주광산경찰서   검거건수   4  10      135   996   1922
광주광산경찰서   검거인원   3   8      129   736   2585
광주광산경찰서     구속   0   4        5    12      6
광주광산경찰서    불구속   0   4       81   639   1181
광주광산경찰서     기타   3   0       43    85   1398

In [133]:
df2016

            구분  살인  강도  강간·강제추행    절도     폭력
관서명
광주지방경찰청계  발생건수  17  47      701  6052   8599
광주지방경찰청계  검거건수  18  47      713  4242   7631
광주지방경찰청계  검거인원  21  54      758  3455  10747
광주지방경찰청계    구속  14  25       37   132     57
광주지방경찰청계   불구속   3  25      491  2862   5267
광주지방경찰청계    기타   4   4      230   461   5423
광주동부경찰서   발생건수   3   8       83   832   1142
광주동부경찰서   검거건수   3   7       70   679   1002
광주동부경찰서   검거인원   4  10       71   543   1497
광주동부경찰서     구속   2   2        3    17      7
광주동부경찰서    불구속   0   7       50   460    773
광주동부경찰서     기타   2   1       18    66    717
광주서부경찰서   발생건수   2  11      174  1417   2288
광주서부경찰서   검거건수   3  11      158   963   1994
광주서부경찰서   검거인원   3  13      169   894   2874
광주서부경찰서     구속   3   6        7    22     18
광주서부경찰서    불구속   0   4       92   749   1301
광주서부경찰서     기타   0   3       70   123   1555
광주남부경찰서   발생건수   1   4       64   768   1028
광주남부경찰서   검거건수   1   4       54   544    883
광주남부경찰서   검거인원   1   5       55   348   1198
광주남부경찰서     구속   1   4        2    12      2
광주남부경찰서    불구속   0   1       38   264    599
광주남부경찰서     기타   0   0       15    72    597
광주북부경찰서   발생건수   6   7      205  1788   2142
광주북부경찰서   검거건수   5   8      158  1156   1906
광주북부경찰서   검거인원   6  10      178   933   2700
광주북부경찰서     구속   3   6        1    50     13
광주북부경찰서    불구속   2   4      135   759   1402
광주북부경찰서     기타   1   0       42   124   1285
광주광산경찰서   발생건수   5  17      175  1247   1999
광주광산경찰서   검거건수   5  17      147   898   1798
광주광산경찰서   검거인원   6  16      147   723   2382
광주광산경찰서     구속   4   7       14    31      7
광주광산경찰서    불구속   1   9       85   620   1125
광주광산경찰서     기타   1   0       48    72   1250

In [134]:
df2017

            구분  살인  강도  강간·강제추행    절도     폭력
관서명
광주지방경찰청계  발생건수   9  33      725  4816   8366
광주지방경찰청계  검거건수   9  32      732  3487   7553
광주지방경찰청계  검거인원  10  61      824  3046  11018
광주지방경찰청계    구속   8  28       71   115     88
광주지방경찰청계   불구속   0  26      523  2493   5235
광주지방경찰청계    기타   2   7      230   438   5695
광주지방경찰청   발생건수   0   0        0     0      0
광주지방경찰청   검거건수   0   1       91     0     37
광주지방경찰청   검거인원   0   1      105     0    149
광주지방경찰청     구속   0   0       17     0      7
광주지방경찰청    불구속   0   1       53     0     69
광주지방경찰청     기타   0   0       35     0     73
광주동부경찰서   발생건수   3   5       77   624   1090
광주동부경찰서   검거건수   3   5       70   470    953
광주동부경찰서   검거인원   4   4       76   483   1538
광주동부경찰서     구속   2   3        2    19      9
광주동부경찰서    불구속   0   1       57   395    801
광주동부경찰서     기타   2   0       17    69    728
광주서부경찰서   발생건수   0   7      196  1142   2293
광주서부경찰서   검거건수   0   7      172   708   2065
광주서부경찰서   검거인원   0  23      188   708   2971
광주서부경찰서     구속   0   8        6    20     31
광주서부경찰서    불구속   0  15      123   582   1356
광주서부경찰서     기타   0   0       59   106   1584
광주남부경찰서   발생건수   0   4       68   577    898
광주남부경찰서   검거건수   0   4       51   522    799
광주남부경찰서   검거인원   0   5       47   363   1107
광주남부경찰서     구속   0   2        1    18      1
광주남부경찰서    불구속   0   2       29   271    591
광주남부경찰서     기타   0   1       17    74    515
광주북부경찰서   발생건수   3   5      215  1546   2176
광주북부경찰서   검거건수   3   5      204  1127   1997
광주북부경찰서   검거인원   3   6      260   898   2863
광주북부경찰서     구속   3   4       39    33     22
광주북부경찰서    불구속   0   0      159   730   1314
광주북부경찰서     기타   0   2       62   135   1527
광주광산경찰서   발생건수   3  12      169   927   1909
광주광산경찰서   검거건수   3  10      144   660   1702
광주광산경찰서   검거인원   3  22      148   594   2390
광주광산경찰서     구속   3  11        6    25     18
광주광산경찰서    불구속   0   7      102   515   1104
광주광산경찰서     기타   0   4       40    54   1268

In [135]:
df2015

            구분  살인  강도  강간·강제추행    절도     폭력
관서명
광주지방경찰청계  발생건수  18  44      750  8425   9593
광주지방경찰청계  검거건수  18  47      758  5409   8301
광주지방경찰청계  검거인원  17  66      776  3433  11774
광주지방경찰청계    구속   9  33       42   104     58
광주지방경찰청계   불구속   1  26      511  2781   5618
광주지방경찰청계    기타   7   7      223   548   6098
광주동부경찰서   발생건수   3   5       92  1100   1155
광주동부경찰서   검거건수   4   6       86   583    970
광주동부경찰서   검거인원   4   7       98   447   1483
광주동부경찰서     구속   3   2        8    13     10
광주동부경찰서    불구속   0   4       63   379    703
광주동부경찰서     기타   1   1       27    55    770
광주서부경찰서   발생건수   5  10      172  2050   2483
광주서부경찰서   검거건수   4   8      153  1471   2124
광주서부경찰서   검거인원   4  15      167   876   3080
광주서부경찰서     구속   3  10        7    27     19
광주서부경찰서    불구속   0   5       91   665   1366
광주서부경찰서     기타   1   0       69   184   1695
광주남부경찰서   발생건수   1   3       70   962   1081
광주남부경찰서   검거건수   1   3       53   506    941
광주남부경찰서   검거인원   1   3       52   418   1260
광주남부경찰서     구속   0   3        3    19      3
광주남부경찰서    불구속   1   0       39   325    675
광주남부경찰서     기타   0   0       10    74    582
광주북부경찰서   발생건수   5  14      256  2570   2621
광주북부경찰서   검거건수   5  18      212  1852   2319
광주북부경찰서   검거인원   5  28      216   948   3168
광주북부경찰서     구속   3  11       11    30     10
광주북부경찰서    불구속   0  12      153   770   1544
광주북부경찰서     기타   2   5       52   148   1614
광주광산경찰서   발생건수   4  12      160  1743   2253
광주광산경찰서   검거건수   4  10      135   996   1922
광주광산경찰서   검거인원   3   8      129   736   2585
광주광산경찰서     구속   0   4        5    12      6
광주광산경찰서    불구속   0   4       81   639   1181
광주광산경찰서     기타   3   0       43    85   1398

In [136]:
# 2015 총계 컬럼 만들기
# 발생한 범죄수를 모두 더한값
df2015["2015총계"] = df2015.sum(axis = 1)
df2015

            구분  살인  강도  강간·강제추행    절도     폭력  2015총계
관서명
광주지방경찰청계  발생건수  18  44      750  8425   9593   18830
광주지방경찰청계  검거건수  18  47      758  5409   8301   14533
광주지방경찰청계  검거인원  17  66      776  3433  11774   16066
광주지방경찰청계    구속   9  33       42   104     58     246
광주지방경찰청계   불구속   1  26      511  2781   5618    8937
광주지방경찰청계    기타   7   7      223   548   6098    6883
광주동부경찰서   발생건수   3   5       92  1100   1155    2355
광주동부경찰서   검거건수   4   6       86   583    970    1649
광주동부경찰서   검거인원   4   7       98   447   1483    2039
광주동부경찰서     구속   3   2        8    13     10      36
광주동부경찰서    불구속   0   4       63   379    703    1149
광주동부경찰서     기타   1   1       27    55    770     854
광주서부경찰서   발생건수   5  10      172  2050   2483    4720
광주서부경찰서   검거건수   4   8      153  1471   2124    3760
광주서부경찰서   검거인원   4  15      167   876   3080    4142
광주서부경찰서     구속   3  10        7    27     19      66
광주서부경찰서    불구속   0   5       91   665   1366    2127
광주서부경찰서     기타   1   0       69   184   1695    1949
광주남부경찰서   발생건수   1   3       70   962   1081    2117
광주남부경찰서   검거건수   1   3       53   506    941    1504
광주남부경찰서   검거인원   1   3       52   418   1260    1734
광주남부경찰서     구속   0   3        3    19      3      28
광주남부경찰서    불구속   1   0       39   325    675    1040
광주남부경찰서     기타   0   0       10    74    582     666
광주북부경찰서   발생건수   5  14      256  2570   2621    5466
광주북부경찰서   검거건수   5  18      212  1852   2319    4406
광주북부경찰서   검거인원   5  28      216   948   3168    4365
광주북부경찰서     구속   3  11       11    30     10      65
광주북부경찰서    불구속   0  12      153   770   1544    2479
광주북부경찰서     기타   2   5       52   148   1614    1821
광주광산경찰서   발생건수   4  12      160  1743   2253    4172
광주광산경찰서   검거건수   4  10      135   996   1922    3067
광주광산경찰서   검거인원   3   8      129   736   2585    3461
광주광산경찰서     구속   0   4        5    12      6      27
광주광산경찰서    불구속   0   4       81   639   1181    1905
광주광산경찰서     기타   3   0       43    85   1398    1529

In [137]:
df2015[df2015["구분"] == "발생건수"].sum(axis = 1)

관서명
광주지방경찰청계    37660
광주동부경찰서      4710
광주서부경찰서      9440
광주남부경찰서      4234
광주북부경찰서     10932
광주광산경찰서      8344
dtype: int64

In [138]:
s1 = df2015[df2015["구분"] == "발생건수"]["2015총계"]

In [139]:
df2016

            구분  살인  강도  강간·강제추행    절도     폭력
관서명
광주지방경찰청계  발생건수  17  47      701  6052   8599
광주지방경찰청계  검거건수  18  47      713  4242   7631
광주지방경찰청계  검거인원  21  54      758  3455  10747
광주지방경찰청계    구속  14  25       37   132     57
광주지방경찰청계   불구속   3  25      491  2862   5267
광주지방경찰청계    기타   4   4      230   461   5423
광주동부경찰서   발생건수   3   8       83   832   1142
광주동부경찰서   검거건수   3   7       70   679   1002
광주동부경찰서   검거인원   4  10       71   543   1497
광주동부경찰서     구속   2   2        3    17      7
광주동부경찰서    불구속   0   7       50   460    773
광주동부경찰서     기타   2   1       18    66    717
광주서부경찰서   발생건수   2  11      174  1417   2288
광주서부경찰서   검거건수   3  11      158   963   1994
광주서부경찰서   검거인원   3  13      169   894   2874
광주서부경찰서     구속   3   6        7    22     18
광주서부경찰서    불구속   0   4       92   749   1301
광주서부경찰서     기타   0   3       70   123   1555
광주남부경찰서   발생건수   1   4       64   768   1028
광주남부경찰서   검거건수   1   4       54   544    883
광주남부경찰서   검거인원   1   5       55   348   1198
광주남부경찰서     구속   1   4        2    12      2
광주남부경찰서    불구속   0   1       38   264    599
광주남부경찰서     기타   0   0       15    72    597
광주북부경찰서   발생건수   6   7      205  1788   2142
광주북부경찰서   검거건수   5   8      158  1156   1906
광주북부경찰서   검거인원   6  10      178   933   2700
광주북부경찰서     구속   3   6        1    50     13
광주북부경찰서    불구속   2   4      135   759   1402
광주북부경찰서     기타   1   0       42   124   1285
광주광산경찰서   발생건수   5  17      175  1247   1999
광주광산경찰서   검거건수   5  17      147   898   1798
광주광산경찰서   검거인원   6  16      147   723   2382
광주광산경찰서     구속   4   7       14    31      7
광주광산경찰서    불구속   1   9       85   620   1125
광주광산경찰서     기타   1   0       48    72   1250

In [140]:
df2016[df2016["구분"] == "발생건수"]

            구분  살인  강도  강간·강제추행    절도    폭력
관서명
광주지방경찰청계  발생건수  17  47      701  6052  8599
광주동부경찰서   발생건수   3   8       83   832  1142
광주서부경찰서   발생건수   2  11      174  1417  2288
광주남부경찰서   발생건수   1   4       64   768  1028
광주북부경찰서   발생건수   6   7      205  1788  2142
광주광산경찰서   발생건수   5  17      175  1247  1999

In [141]:
df2016["2016총계"] = df2016.sum(axis = 1)

In [218]:
s2 = df2016[df2016["구분"] == "발생건수"]["2016총계"]

In [219]:
s1, s2

(관서명
 광주지방경찰청계    18830
 광주동부경찰서      2355
 광주서부경찰서      4720
 광주남부경찰서      2117
 광주북부경찰서      5466
 광주광산경찰서      4172
 Name: 2015총계, dtype: int64,
 관서명
 광주지방경찰청계    15416
 광주동부경찰서      2068
 광주서부경찰서      3892
 광주남부경찰서      1865
 광주북부경찰서      4148
 광주광산경찰서      3443
 Name: 2016총계, dtype: int64)

In [220]:
df2016.index.value_counts()

광주광산경찰서     6
광주남부경찰서     6
광주북부경찰서     6
광주서부경찰서     6
광주동부경찰서     6
광주지방경찰청계    6
Name: 관서명, dtype: int64

In [221]:
df2017.index.value_counts()

광주광산경찰서     6
광주남부경찰서     6
광주북부경찰서     6
광주서부경찰서     6
광주동부경찰서     6
광주지방경찰청계    6
Name: 관서명, dtype: int64

In [222]:
#2016년에는 없지만 2017년에만 있는 데이터 지우는 작업
#df2017에서 광주지방경차청에 해당하는 index들을 모두 삭제
#행을 지워주는 함수는 drop!!!!!!!!!!!!!!!
df2017 = df2017.drop("광주지방경찰청")

KeyError: "['광주지방경찰청'] not found in axis"

In [223]:
df2017["2017총계"] = df2017.sum(axis = 1)
s3 = df2017[df2017["구분"] == "발생건수"]["2017총계"]

<ipython-input-223-5857d9baae32>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2017["2017총계"] = df2017.sum(axis = 1)

In [224]:
s1

관서명
광주지방경찰청계    18830
광주동부경찰서      2355
광주서부경찰서      4720
광주남부경찰서      2117
광주북부경찰서      5466
광주광산경찰서      4172
Name: 2015총계, dtype: int64

In [225]:
# 2016-2015 증감율
s2_s1 = (s2-s1) / s1 * 100
s2_s1

관서명
광주지방경찰청계   -18.130643
광주동부경찰서    -12.186837
광주서부경찰서    -17.542373
광주남부경찰서    -11.903637
광주북부경찰서    -24.112697
광주광산경찰서    -17.473634
dtype: float64

In [235]:
# 2017-2016 증감율
s3_s2 = (s3-s2) / s2 * 100

In [236]:
# 1. 데이터 프레임 형성 : pd.DataFrame
# 데이터 프레임 함수에서는 axis 사용 못한다.
# 데이터 프레임 함수에서는 모든 데이터들을 같은 타입으로 처리를 해주기 때문에 실수형으로 출력된다. 이를 타입 바꿔주는 작업 필요
result = pd.DataFrame([s1, s2_s1, s2, s3_s2, s3]).T

In [245]:
s2_s1.name = "2015-2016 증감율"

In [246]:
s3_s2.name = "2016-2017 증감율"

In [248]:
result

          2015총계  2015-2016 증감율  2016총계  2016-2017 증감율  2017총계
관서명
광주지방경찰청계   18830     -18.130643   15416      80.967826   27898
광주동부경찰서     2355     -12.186837    2068      73.984526    3598
광주서부경찰서     4720     -17.542373    3892      86.947585    7276
광주남부경찰서     2117     -11.903637    1865      65.898123    3094
광주북부경찰서     5466     -24.112697    4148      90.212150    7890
광주광산경찰서     4172     -17.473634    3443      75.428405    6040

In [249]:
result['2015총계'] = result['2015총계'].astype('int64')

In [250]:
# 2. 데이터 프레임 병합 : pd.concat
result = pd.concat([s1, s2_s1, s2, s3_s2, s3], axis = 1)
result

          2015총계  2015-2016 증감율  2016총계  2016-2017 증감율  2017총계
관서명
광주지방경찰청계   18830     -18.130643   15416      80.967826   27898
광주동부경찰서     2355     -12.186837    2068      73.984526    3598
광주서부경찰서     4720     -17.542373    3892      86.947585    7276
광주남부경찰서     2117     -11.903637    1865      65.898123    3094
광주북부경찰서     5466     -24.112697    4148      90.212150    7890
광주광산경찰서     4172     -17.473634    3443      75.428405    6040